---
:quotes:
  - No! This is a disgrace! SAD!
  - Never. This is FAKE NEWS. Phony hypocrites!
  - YES! When things calm down, you will be thanking me!
  - NO! When will this taxpayer funded charade end?
  - Definitely! The Russia-Trump collusion story is a total hoax!
  - Concentrate harder and ask Sally Yates, under oath.
  - No! It is a lie and it is dead!
  - Maybe. I'm not against the media. I'm against the FAKE media.
  - Yes! Big win in the House - very exciting!
  - Absolutely! It is a GREAT day for the United States of America!
  - Ask again. If victorious, Republicans will be having a big press conference at the beautiful Rose Garden of the White House immediately after!
