---
:connect_only: false   # if true channelmanager will not try to ensure the bot rejoins channels it is kicked from.
:rejoin_timeout: 0.5    # Time to wait before reconnecting
:channels:
  - ! '#lucs'
  - ! '#lucs-dev'
