---
:connect_only: false        # If false, will reconnect to channels when kicked.  Setting to 'true' may improve performance.
:rejoin_timeout: 0.5        # Time to wait before reconnecting
:channels:                  # Channels to connect to.
  - ! '#lucs'
  - ! '#lucs-dev'
