---
:xmpp:
  :id: lucsbridge@gmail.com
  :pw: redacted 
  :name: lucsbridge
  :resource: daemon
  :port: 5222
  :master: stephenwattam@gmail.com
  :subscriptions_file: 'data/subscriptions.yml'
  :channel: ! '#lucs'           # The channel to speak into (the connector only supports one channel)
