--- 
:gems:
  - time_ago_in_words
  - sqlite3
# Storage config
:database_path:  "data/logs.db"
:auto_wildcard: true            # If set to true, will automatically wrap *expressions*
:case_sensitive: false          # If set to false, the script will attempt to rewrite input to be case-insensitive.  May be slow.
:pragma:
  #"locking_mode": "EXCLUSIVE"
  "cache_size": 20000
  "synchronous": 0
  "temp_store": 2
:verbose: false 
:max_results: 3

