---
:gems:
  - romegle
:use_nick: false        # Should all messages be sent with a nick (<nick> msg)
:single_name: omegle    # name used when one person is talking
:spy_namelist:          # names randomly assigned in spy mode
  - Alice
  - Bob
  - Charles
  - Dan
  - Eric
  - Frank
  - Gus
  - Harry
  - Ian
  - Jack
  - Kevin
  - Larry
  - Martin
  - Nick
  - Oliver
  - Paul
  - Quentin
  - Ralph
  - Sydney
  - Tom
  - Uri
  - Vicky
  - Walter
  - Xavier
  - Yvette
  - Zan

