--- 
# Storage config
:database_path:  "data/r9k.db"
:warning_path:   "data/r9k.bans.yml"
:warnings:       2                          # The starting score
:recovery_rate:  0.02                       # Added to score every time someone doesn't repeat something
:max_recovery:   3                          # the maximum allowed score
:reason:         "Too many repetitions (score: %d < 0)"
:pragma:
  "locking_mode": "EXCLUSIVE"
  "cache_size": 20000
  "synchronous": 0
  "temp_store": 2
:table:          "msg"
:field:          "hash"


