---
:bot_connection_poll_rate: 120          # Check every n seconds that the bot is still conected
:daemonise: true
:irc:
  :connect_timeout: 10                  # How long to check we're connected if verify is true
  :nick: ^LUGod                         # The nickname to use
  :user: LUGod                          # The username for IRC
  :name: LU Master of All               # The full name of the user
  :password: lugodpass                  # Nick auth
  :server: irc.freenode.net             # The server
  :channel: ! '#lucs'                   # El channel
  :port: 6667                           # Port
  :verbose: false                       # turn logging on/off for the bot
:hooks:
  :dir: services/                       # Where service objects are located
  :config_dir: config/services/         # Where service objects' config files are located
  :objs:                                # A list of service object names (instantiated with eval)
    # - Echo
    - TitleService
    - SpellService
    - ReminderService 
    - WolframService 
    - LogService
    - PingService 
    - InfoService
:logging:                               # Logging config
  :progname: LUGod                      # The name of the app in the logs
  :logs:                                # A list of places to log to
    :default:                            
      :dev: STDOUT                                                # STDOUT, STDERR or a filename are supported
      :level: :info                                                 # level to debug at
    #:errors:
      #:dev: 'logs/client.err'
      #:level: :warn                                              
    :file_log:
      :dev: 'logs/lugod.log'
      :level: :info
:environments:
  :debug:                               # This is merged with the config below to override it when testing
    :daemonise: false 
    :irc:
      :nick: ^LUGod_dbg
      :password:                      # the test nick is not registered
      :channel: ! '#lucs-dev'
      :verbose: false                  # Enable/disable bot level logging
    # :hooks:
    #   :objs:
    #     - Echo
    #     - PingService
    #     - TitleService
    #     - InfoService
    :logging:
      :logs:
        :default:
          :level: :debug
        :file_log:
          :level: :debug
  :testing:                               
    :daemonise: false 
    :irc:
      :nick: ^LUGod_test
      :password:                      # the test nick is not registered
      :channel: ! '#lucs-dev'
